### ISSUE TITLE
Long line wrapping - duplicated new line

### ISSUE THREAD

**Issue by gwenn** [SolraBizna/liso#1] opened 2022-12-17 10:37 UTC
I get
```sh
lish> abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrs

t 
```
instead of
```sh
lish> abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrs
t 
```
I see these commands with `kitty --dump-commands`:
```
draw s
screen_cursor_down 1
screen_cursor_back1 78
screen_carriage_return
screen_linefeed
draw
screen_carriage_return
screen_set_mode 25 1
```

**Comment by SolraBizna** [comment] 2022-12-18 19:24
This is with an 80-column terminal, right? In iTerm2 and Konsole, when I try to reproduce this, I see the `t` on the same line as the rest of the input, in the 80th column. My first guess as to what's going on would be that kitty isn't emulating the line wrap mode command correctly.

**Comment by gwenn** [comment] 2022-12-19 18:29
With `kitty`, I've just tried these libraries:
- linenoise OK
- replxx OK
- liner OK
- linefeed OK
- termwiz OK
- reedline OK

And I managed to reproduce the bug with `iterm2`: just copy/paste `abcdefghijklmnopqrstuvwxyz_0123456789` twice.

**Comment by SolraBizna** [comment] 2022-12-24 19:50
Okay, it sounds like the bug is indeed in liso. :)

> And I managed to reproduce the bug with `iterm2`: just copy/paste `abcdefghijklmnopqrstuvwxyz_0123456789` twice.

I tried that on my end, and while that doesn't work on its own, if I paste it twice, erase all, then paste twice *again* that does reproduce it. I'll try to figure out what's going on in here.

Sorry for my slow responses.

Edit: I can also reproduce it by filling a line with characters, deleting the last character, and typing another character. Every time I delete and type, it adds another line.

**Comment by SolraBizna** [comment] 2022-12-24 20:42
16bbed4 should fix this. I'm not happy with my solution (I'm not happy with that whole *function*) but if it works, it works. If you can confirm it fixes it at your end, close the issue and I'll publish this commit as 0.7.1.

Thank you for finding this bug, and providing a reproducer.

**Comment by gwenn** [comment] 2022-12-25 17:53
With `liso` up to date and `iterm2`, when i copy paste `abcdefghijklmnopqrstuvwxyz_0123456789` twice, the cursor is kept on the first line while it should have been at the beginning of the second line.

**Comment by SolraBizna** [comment] 2022-12-25 20:14
That's actually intended behavior. Additional lines will be added at the bottom only once there is actual text to put on them.

But now that I've said that out loud, I realize that I can't think of any other readline-alike that operates that way...

**Comment by SolraBizna** [comment] 2022-12-26 00:14
I won't have time until next year to test this thoroughly, but c907549 would seem to resolve this with minimal impact to the code. I'd like to rewrite all the output sync code, but this should work for now.

**Comment by SolraBizna** [comment] 2024-06-03 23:06
I believe this bug is fixed, and there has been no new activity on this bug.

**Closed as completed by SolraBizna** 2024-06-03 23:06 UTC
